# Generated by Django 4.1.6 on 2023-06-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_answer_choice_question_delete_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choice')),
            ],
        ),
    ]
