# Generated by Django 4.1.6 on 2023-06-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_survey_delete_answerstatistics_answer_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AddField(
            model_name='responsechoice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_choices', to='questionnaire.answer'),
        ),
        migrations.AddField(
            model_name='responsechoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choice'),
        ),
    ]
