# Generated by Django 4.1.6 on 2023-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_answer_choice_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('open', 'Открытый вопрос')], max_length=20),
        ),
    ]
