# Generated by Django 4.1.6 on 2023-06-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_remove_choice_choice_text_choice_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice_text',
        ),
    ]
