# Generated by Django 4.1.6 on 2023-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, error_messages={'required': 'Поле "Вопрос" обязательно для заполнения'}, max_length=255, null=True),
        ),
    ]
