# Generated by Django 4.1.6 on 2023-06-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_alter_question_question_text_questionstat_choicestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionstat',
            name='question',
        ),
        migrations.DeleteModel(
            name='ChoiceStat',
        ),
        migrations.DeleteModel(
            name='QuestionStat',
        ),
    ]
