# Generated by Django 4.1.6 on 2023-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_delete_questionstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
    ]
