# Generated by Django 4.1.6 on 2023-06-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_question_num_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_responses',
        ),
    ]
