# Generated by Django 4.1.6 on 2023-06-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_remove_question_num_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='num_of_comp',
            field=models.IntegerField(default=0),
        ),
    ]
